// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config initializations
 * Place the definition of custom battle configuration initializations in this file.
 *
 * Do not forget to add a comma at the end of the line, if you want to add another config
 *
 * Format:
 *	 { "name", &battle_config.<variable name>, <default value>, <minimum value>, <maximum value> },
 **/
{ "item_drop_common_min_boss",	&battle_config.item_drop_common_min_boss,	1,		0,	10000,	},
{ "item_drop_common_min_mvp",	&battle_config.item_drop_common_min_mvp,	1,		0,	10000,	},
{ "item_drop_common_max_boss",	&battle_config.item_drop_common_max_boss,	10000,	1,	10000,	},
{ "item_drop_common_max_mvp",	&battle_config.item_drop_common_max_mvp,	10000,	1,	10000,	},
{ "item_drop_equip_min_boss",	&battle_config.item_drop_equip_min_boss,	1,		0,	10000,	},
{ "item_drop_equip_min_mvp",	&battle_config.item_drop_equip_min_mvp,		1,		0,	10000,	},
{ "item_drop_equip_max_boss",	&battle_config.item_drop_equip_max_boss,	10000,	1,	10000,	},
{ "item_drop_equip_max_mvp",	&battle_config.item_drop_equip_max_mvp,		10000,	1,	10000,	},
{ "item_drop_card_min_boss",	&battle_config.item_drop_card_min_boss,		1,		0,	10000,	},
{ "item_drop_card_min_mvp",		&battle_config.item_drop_card_min_mvp,		1,		0,	10000,	},
{ "item_drop_card_max_boss",	&battle_config.item_drop_card_max_boss,		10000,	1,	10000,	},
{ "item_drop_card_max_mvp",		&battle_config.item_drop_card_max_mvp,		10000,	1,	10000,	},
{ "item_drop_heal_min_boss",	&battle_config.item_drop_heal_min_boss,		1,		0,	10000,	},
{ "item_drop_heal_min_mvp",		&battle_config.item_drop_heal_min_mvp,		1,		0,	10000,	},
{ "item_drop_heal_max_boss",	&battle_config.item_drop_heal_max_boss,		10000,	1,	10000,	},
{ "item_drop_heal_max_mvp",		&battle_config.item_drop_heal_max_mvp,		10000,	1,	10000,	},
{ "item_drop_use_min_boss",		&battle_config.item_drop_use_min_boss,		1,		0,	10000,	},
{ "item_drop_use_min_mvp",		&battle_config.item_drop_use_min_mvp,		1,		0,	10000,	},
{ "item_drop_use_max_boss",		&battle_config.item_drop_use_max_boss,		10000,	1,	10000,	},
{ "item_drop_use_max_mvp",		&battle_config.item_drop_use_max_mvp,		10000,	1,	10000,	},

