// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

int item_drop_heal_min_mvp;
int item_drop_heal_min_boss;
int item_drop_heal_max_mvp;
int item_drop_heal_max_boss;
int item_drop_use_min_mvp;
int item_drop_use_min_boss;
int item_drop_use_max_mvp;
int item_drop_use_max_boss;
int item_drop_equip_min_mvp;
int item_drop_equip_min_boss;
int item_drop_equip_max_mvp;
int item_drop_equip_max_boss;
int item_drop_card_min_mvp;
int item_drop_card_min_boss;
int item_drop_card_max_mvp;
int item_drop_card_max_boss;
int item_drop_common_min_mvp;
int item_drop_common_min_boss;
int item_drop_common_max_mvp;
int item_drop_common_max_boss;
